### ISSUE TITLE
Não consegui instalar

### ISSUE THREAD

**Issue by celsodavid** [marcelod/codeistrap#1]
Caro marcelod,
Fui testar sua ideia, porém não consegui instalar pois ao acessar http://localhost/codeistrap/instalar (local, na minha maquina) aparece a mensagem "No input file specified. " e mesmo olhando o codigo não consegui detectar o problema se possivel gostaria de uma ajuda sua.

Obrigado

**Comment by marcelod** [comment]
Valew, algo que posso pensar em dar uma atenção maior.
